from pydantic import BaseModel, Field
from typing import List, Optional
from typing import Dict, Any

class RAGQueryRequest(BaseModel):
    query: str = Field(..., description="The user complaint or domain question to analyze.")
    top_k: Optional[int] = Field(default=3, description="Number of source context items to pass to Gemini.")

class RAGQueryResponse(BaseModel):
    query: str
    answer: str = Field(..., description="The definitive response generated by Gemini, grounded in context.")
    context_retrieved: List[str] = Field(..., description="Actual text strings extracted from the Vector Engine.")



class QueryRequest(BaseModel):
    query: str

class RAGResponse(BaseModel):
    query: str
    answer: str
    context: List[str]

class MemorySearchResponse(BaseModel):
    incidents: List[Dict[str, Any]]
