"""create_analytics_snapshot_table

Revision ID: 0c3f54ff9c36
Revises: bc4f52996e9b
Create Date: 2026-06-20 21:49:50.504640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3f54ff9c36'
down_revision: Union[str, None] = 'bc4f52996e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshot',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshot_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshot_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_snapshot_key'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshot_id'))

    op.drop_table('analytics_snapshot')
    # ### end Alembic commands ###
